# Generated by Django 4.1.2 on 2022-12-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HM_FoundationApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="ec_post", name="name",),
        migrations.AddField(
            model_name="executive_counsil",
            name="ec_number",
            field=models.CharField(max_length=264, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="executive_counsil",
            name="ec_post",
            field=models.CharField(max_length=264, null=True, unique=True),
        ),
        migrations.DeleteModel(name="EC_Number",),
        migrations.DeleteModel(name="EC_Post",),
    ]
