# Generated by Django 4.1.2 on 2022-12-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HM_FoundationApp", "0003_alter_executive_counsil_ec_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adviser_Counsil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ac_name", models.CharField(max_length=264)),
                ("ac_post", models.CharField(max_length=264, null=True)),
                ("ac_number", models.CharField(max_length=264, null=True)),
            ],
        ),
    ]
