# Generated by Django 4.1.2 on 2023-01-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HM_FoundationApp", "0004_adviser_counsil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news", models.CharField(max_length=3168)),
            ],
        ),
    ]
