# Generated by Django 4.1.2 on 2023-01-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HM_FoundationApp", "0005_add_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="HMK_Foundation/static/assets")),
            ],
        ),
    ]
